### ISSUE TITLE
datim.org/api/sqlviews is not publicly available 

### ISSUE THREAD

**Issue by jaliasd** [USAID-OHA-SI/tameDP#6]
![image](https://user-images.githubusercontent.com/8836685/54087815-c0604700-435f-11e9-8427-89a5211f9c0f.png)

Per pickering, these url's aren't public as of last week

12  -- 1 columns 2 columns  'https://www.datim.org/api/sqlViews/fgUtV6e9YIX/data.csv'
 33  -- 1 columns 2 columns  'https://www.datim.org/api/sqlViews/fgUtV6e9YIX/data.csv'
 35  -- 1 columns 3 columns  'https://www.datim.org/api/sqlViews/fgUtV6e9YIX/data.csv'
 58  -- 1 columns 33 columns 'https://www.datim.org/api/sqlViews/fgUtV6e9YIX/data.csv'

**Comment by achafetz** [comment]
Hmm. Why the change? 

This would then affect ICPIutilities::rename_offical() as well then.

**Comment by jaliasd** [comment]
As usual @jason-p-pickering was cryptic. A priori, there is nothing confidential about that start and end date of a mech, so he sent a request to Irum to ask about making it public.

**Comment by jaliasd** [comment]
@achafetz I got the package to run by turning off my wireless, but maybe modify `get_names` to revert to the other half of the `else` command if it can't access datim.org? Just a thought.

**Comment by achafetz** [comment]
so, now that I'm sitting in from of my computer instead of at the airport, I looked into this.

![image](https://user-images.githubusercontent.com/8933069/54225493-d8c19480-450c-11e9-8b34-e32dc2357371.png)

I changed the options about a week ago to allow users to not map the infro from DATIM

`tame_dp("~/Downloads/V17_DataPack_South Sudan_03082019_11pm.xlsx", map_names = FALSE)`

That said, it still should probably add the OU name from the main DP tab if this option is selected or you couldn't access DATIM.

(maybe I need to reset my cookies, but I'm logged out and can still get the SQL view)

**Comment by achafetz** [comment]
@jason-p-pickering, I cleared out my cache and still can access this SQL view. Any thoughts on how that's possible if these are now private?
